package GUI;

import héroes.y.villanos.Personaje;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ListaDePersonajes extends javax.swing.JFrame {
    private ArrayList<Personaje> lpersonajes;
    protected JFrame principal;
    int seleccion;
    
    public ListaDePersonajes(ArrayList<Personaje> lp, JFrame ppal){
        initComponents(); 
        lpersonajes = lp;
        principal = ppal;
        for(int i=0; i < lp.size(); i++) {
           Personaje pj = lp.get(i);
           lista.addItem(pj.getNombre());
        }
        frase.setEnabled(false);
        equiparImple.setEnabled(false);
        usarPoder.setEnabled(false);
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lista = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        informacion = new javax.swing.JTextArea();
        usarPoder = new javax.swing.JButton();
        equiparImple = new javax.swing.JButton();
        frase = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ListaDePersonajes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Lista de personajes");

        lista.setForeground(new java.awt.Color(51, 153, 255));
        lista.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        informacion.setColumns(20);
        informacion.setRows(5);
        informacion.setEnabled(false);
        jScrollPane1.setViewportView(informacion);

        usarPoder.setText("Usar Poder");
        usarPoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usarPoderActionPerformed(evt);
            }
        });

        equiparImple.setText("Equipar Implemento");
        equiparImple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiparImpleActionPerformed(evt);
            }
        });

        frase.setText("Frase");
        frase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fraseActionPerformed(evt);
            }
        });

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usarPoder)
                .addGap(18, 18, 18)
                .addComponent(equiparImple)
                .addGap(18, 18, 18)
                .addComponent(frase)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(10, 10, 10)
                .addComponent(jButton5)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usarPoder)
                    .addComponent(equiparImple)
                    .addComponent(frase)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        principal.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed

        seleccion = lista.getSelectedIndex();
        if(seleccion == 0){
            JOptionPane.showMessageDialog(null, "Por favor seleccionar el tipo de personaje", "Validación", JOptionPane.INFORMATION_MESSAGE);
            informacion.setText(""); 
       }else{
            frase.setEnabled(true);
            equiparImple.setEnabled(true);
            usarPoder.setEnabled(true);
            seleccion = lista.getSelectedIndex() - 1;
            Personaje personaje = lpersonajes.get(seleccion);
        
            informacion.setText("\n" + "Soy un " + (personaje.getClass().getName()).substring(18) + 
                                "\n" + "Mi nombre es " + personaje.getNombre() + 
                                "\n" + "Tengo/Puedo ");  
                                    for(int i = 0; i < personaje.getPoder().size(); i++){
                                        if(i == personaje.getPoder().size() - 1){ informacion.setText(informacion.getText() + personaje.getPoder().get(i)); }
                                        else { informacion.setText(informacion.getText() + personaje.getPoder().get(i) + ", "); }
                                    }
            informacion.setText(informacion.getText() + "\n" + "Uso ");    
                                    for(int i = 0; i < personaje.getImplemento().size(); i++){
                                        if(i == personaje.getImplemento().size() - 1) { informacion.setText(informacion.getText() + personaje.getImplemento().get(i)); }
                                        else { informacion.setText(informacion.getText() + personaje.getImplemento().get(i) + ", "); }
                                    }
            informacion.setText(informacion.getText() + "\n" + personaje.getFrase() +
                                "\n \n" + personaje.gritoCombate());
        }
    }//GEN-LAST:event_listaActionPerformed

    private void fraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fraseActionPerformed
            Personaje personaje = lpersonajes.get(seleccion);
            personaje.emplearFrase(personaje.getNombre(), personaje.getFrase());
    }//GEN-LAST:event_fraseActionPerformed

    private void usarPoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usarPoderActionPerformed
        UsarPoder abrir = new UsarPoder(lpersonajes, seleccion);
        abrir.setVisible(true);
        
    }//GEN-LAST:event_usarPoderActionPerformed

    private void equiparImpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiparImpleActionPerformed
        EquiparImplemento abrir = new EquiparImplemento(lpersonajes, seleccion);
        abrir.setVisible(true);
    }//GEN-LAST:event_equiparImpleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDePersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDePersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDePersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDePersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ListaDePersonajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton equiparImple;
    private javax.swing.JButton frase;
    private javax.swing.JTextArea informacion;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox lista;
    private javax.swing.JButton usarPoder;
    // End of variables declaration//GEN-END:variables
}
